# Generated by Django 5.1.3 on 2024-12-15 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_audit_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company'),
        ),
    ]
