# Generated by Django 5.1.3 on 2024-12-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_audit_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20),
        ),
    ]
