# Generated by Django 5.1.3 on 2024-12-31 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_leaveapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='sent_to',
        ),
    ]
