# Generated by Django 5.1.3 on 2025-01-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_performancereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('PENDING', 'PENDING'), ('OVERDUE', 'OVERDUE')], default='PENDING', max_length=20),
        ),
    ]
