# Generated by Django 5.1.3 on 2025-01-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment_status'),
        ('core', '0009_remove_leaveapplication_sent_to'),
    ]

    operations = [
    ]
