# Generated by Django 5.1.3 on 2025-01-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20250103_1919'),
        ('core', '0011_payroll'),
    ]

    operations = [
    ]
